services:
  - type: web
    name: llm-code-deployment
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AIPIPE_TOKEN
        sync: false
      - key: STUDENT_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
